"use client";

import { TabBar } from "@/components/atoms";
import { TTabItem } from "@/components/atoms/TabBar";
import { cn } from "@/lib/utils";
import Image from "next/image";
import { useMemo, useState } from "react";
import AIIcon from "@/public/assets/svgs/icons/other/ai.svg";
import TargetArrowIcon from "@/public/assets/svgs/icons/other/target_arrow.svg";
import SkillsGroup from "../SkillsGroup";
import TalentProfileJobCardGroup, {
  TalentProfileJobCardGroupItem,
} from "../TalentProfileJobCardGroup";
import ProfileSectionActions from "./ProfileSectionActions";

export type WorkHistoryWorklancTab = TTabItem;

export interface FreelancerProfileWorkHistoryWorklancProps {
  id?: string;
  className?: string;
  title?: string;
  tabs: WorkHistoryWorklancTab[];
  jobs: TalentProfileJobCardGroupItem[];
  matchedSearchSkills?: string[];
  searchSkills?: string[];
  summary?: string;
  summarySkills?: string[];
  showSearchSkills?: boolean;
  showSummary?: boolean;
  selectedTabIndex?: number;
  onTabChange?: (index: number) => void;
  onEdit?: () => void;
  onRemove?: () => void;
}

export default function FreelancerProfileWorkHistoryWorklanc({
  id = "work_history",
  className,
  title = "Work history on Worklanc",
  tabs,
  jobs,
  matchedSearchSkills = [],
  searchSkills = [],
  summary,
  summarySkills = [],
  showSearchSkills = true,
  showSummary = true,
  selectedTabIndex: controlledTabIndex,
  onTabChange,
  onEdit,
  onRemove,
}: FreelancerProfileWorkHistoryWorklancProps) {
  const [internalTabIndex, setInternalTabIndex] = useState(0);
  const selectedTabIndex = controlledTabIndex ?? internalTabIndex;
  const handleTabChange = onTabChange ?? setInternalTabIndex;

  const filteredJobs = useMemo(() => {
    const selectedTab = tabs[selectedTabIndex]?.value;
    if (!selectedTab || selectedTab === "search_related") return jobs;
    return jobs.filter((job) => job.status === selectedTab);
  }, [jobs, selectedTabIndex, tabs]);

  return (
    <section
      id={id}
      className={cn(
        "space-y-6 rounded-3xl border border-slate-300 p-6",
        className
      )}
    >
      <div className="flex items-center justify-between">
        <h2 className="flex-1 text-2xl font-medium">{title}</h2>
        <ProfileSectionActions onEdit={onEdit} onRemove={onRemove} />
      </div>

      {showSearchSkills && searchSkills.length > 0 && (
        <div className="space-y-6 rounded-3xl border border-slate-300 p-6">
          <div className="flex items-center gap-2">
            <Image
              src={TargetArrowIcon}
              alt="Target arrow"
              className="size-8"
            />
            <h3 className="text-xl font-medium">Skills that match your search</h3>
          </div>

          <SkillsGroup
            skills={searchSkills}
            matchedSkills={matchedSearchSkills}
          />
        </div>
      )}

      {showSummary && summary && (
        <div className="space-y-6 rounded-3xl bg-slate-50 p-4">
          <div className="flex items-center gap-2">
            <Image src={AIIcon} alt="AI" className="size-8" />
            <h3 className="text-xl font-medium">Summary</h3>
          </div>

          <p className="text-sm text-slate-600">{summary}</p>

          <p className="text-xs text-slate-600">
            Generated by CHRLE, Worklanc&apos;s Charlie Unicorn AI, from
            completed jobs
          </p>

          {summarySkills.length > 0 && (
            <div className="space-y-2">
              <p className="text-lg font-medium">Skills used</p>
              <ul className="flex flex-wrap items-center gap-2">
                {summarySkills.map((skill) => (
                  <li
                    key={skill}
                    className="cursor-pointer rounded-md bg-slate-200 px-2 py-0.5 text-sm"
                  >
                    {skill}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      <div>
        <TabBar
          tabs={tabs}
          selectedTabIndex={selectedTabIndex}
          onTab={handleTabChange}
        />
        <TalentProfileJobCardGroup items={filteredJobs} />
      </div>
    </section>
  );
}
