export { default as CatLayout } from "./cat";
export { default as IntroLayout } from "./IntroLayout";
export { default as NavLayout } from "./NavLayout";
export { default as ServicesCatLayout } from "./ServicesCatLayout";
export { default as ServicesLayout } from "./ServicesLayout";
export { default as ServicesSubcatLayout } from "./ServicesSubcatLayout";
export { default as FreelancerLayout } from "./freelancers";
export { default as FreelancerSettingsLayout } from "./freelancers/SettingsLayout";
export { default as ClientLayout } from "./client";
export { default as JobPostLayout } from "./client/JobPostLayout";
export { default as ClientSettingsLayout } from "./client/SettingsLayout";
export { default as OrgManagementLayout } from "./org-management";
export { default as WmLayout } from "./wm";
export { CreateProfilePageLayout } from "./create-profile/CreateProfilePageLayout";
export { ClientOnboardingLayout } from "./client-onboarding/ClientOnboardingLayout";
export { default as BenchLayout } from "./browse/BenchLayout";
